set_property PACKAGE_PIN Y16 [get_ports {ButtonsIn[3]}]
set_property PACKAGE_PIN K19 [get_ports {ButtonsIn[2]}]
set_property PACKAGE_PIN K18 [get_ports {ButtonsIn[0]}]
set_property PACKAGE_PIN P16 [get_ports {ButtonsIn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ButtonsIn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ButtonsIn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ButtonsIn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ButtonsIn[0]}]

set_property PACKAGE_PIN M17 [get_ports {LEDsOut[5]}]
set_property PACKAGE_PIN Y12 [get_ports {LEDsOut[4]}]
set_property PACKAGE_PIN D18 [get_ports {LEDsOut[3]}]
set_property PACKAGE_PIN G14 [get_ports {LEDsOut[2]}]
set_property PACKAGE_PIN M15 [get_ports {LEDsOut[1]}]
set_property PACKAGE_PIN M14 [get_ports {LEDsOut[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDsOut[0]}]

set_property PACKAGE_PIN T16 [get_ports {Switches[3]}]
set_property PACKAGE_PIN W13 [get_ports {Switches[2]}]
set_property PACKAGE_PIN P15 [get_ports {Switches[1]}]
set_property PACKAGE_PIN G15 [get_ports {Switches[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[0]}]

set_property PACKAGE_PIN J15 [get_ports IO_dio]
set_property PACKAGE_PIN H15 [get_ports O_scl]
set_property IOSTANDARD LVCMOS33 [get_ports IO_dio]
set_property IOSTANDARD LVCMOS33 [get_ports O_scl]

set_property PACKAGE_PIN V15 [get_ports ADCChipSelect]
set_property PACKAGE_PIN W15 [get_ports ADCSend]
set_property PACKAGE_PIN T11 [get_ports ADCReceive]
set_property PACKAGE_PIN T10 [get_ports ADCClock]
set_property IOSTANDARD LVCMOS33 [get_ports ADCChipSelect]
set_property IOSTANDARD LVCMOS33 [get_ports ADCSend]
set_property IOSTANDARD LVCMOS33 [get_ports ADCReceive]
set_property IOSTANDARD LVCMOS33 [get_ports ADCClock]

set_property PACKAGE_PIN U7 [get_ports BTTXD]
set_property PACKAGE_PIN V6 [get_ports BTRXD]
set_property IOSTANDARD LVCMOS33 [get_ports BTTXD]
set_property IOSTANDARD LVCMOS33 [get_ports BTRXD]

set_property PACKAGE_PIN Y7 [get_ports PeltierDirectionOut]
set_property PACKAGE_PIN W8 [get_ports PWM1FanInsideSignal]
set_property PACKAGE_PIN Y6 [get_ports PWM2FanOutsideSignal]
set_property PACKAGE_PIN V7 [get_ports PWM3LightSignal]
set_property PACKAGE_PIN W6 [get_ports PWM4PeltierSignal]
set_property PACKAGE_PIN T12 [get_ports SensorDoor]
set_property PACKAGE_PIN U12 [get_ports SensorVibe]
set_property PACKAGE_PIN V8 [get_ports HouseOnOff]
set_property IOSTANDARD LVCMOS33 [get_ports PeltierDirectionOut]
set_property IOSTANDARD LVCMOS33 [get_ports PWM1FanInsideSignal]
set_property IOSTANDARD LVCMOS33 [get_ports PWM2FanOutsideSignal]
set_property IOSTANDARD LVCMOS33 [get_ports PWM3LightSignal]
set_property IOSTANDARD LVCMOS33 [get_ports PWM4PeltierSignal]
set_property IOSTANDARD LVCMOS33 [get_ports SensorDoor]
set_property IOSTANDARD LVCMOS33 [get_ports SensorVibe]
set_property IOSTANDARD LVCMOS33 [get_ports HouseOnOff]

#create_clock -period 8.000 -name ClockIn -waveform {0.000 4.000} [get_ports ClockIn]
set_property PACKAGE_PIN K17 [get_ports ClockIn]
set_property IOSTANDARD LVCMOS33 [get_ports ClockIn]