set_property -dict { PACKAGE_PIN G15 IOSTANDARD LVCMOS33 } [ get_ports a]
set_property -dict { PACKAGE_PIN P15 IOSTANDARD LVCMOS33 } [ get_ports b]
set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS33 } [ get_ports clk]
set_property -dict { PACKAGE_PIN M15 IOSTANDARD LVCMOS33 } [ get_ports l1]
set_property -dict { PACKAGE_PIN G14 IOSTANDARD LVCMOS33 } [ get_ports l2]
set_property -dict { PACKAGE_PIN D18 IOSTANDARD LVCMOS33 } [ get_ports l3]